name: 'Composite Action Recipe'
author: 'Mateusz Zdrenka'
description: 'Greets a user, returns 42, and can thank issue reporters with a comment'

inputs:
  who-to-greet:
    description: 'Name or handle of the person to greet'
    required: true
    default: 'Świat'
outputs:
  answer:
    description: "The answer to life, the universe, and everything"
    value: ${{ steps.greet.outputs.answer }}
branding:
  icon: message-square
  color: blue

runs:
  using: 'composite'
  steps:
    - id: greet
      name: Greet user and set output
      uses: actions/github-script@v6
      with:
        script: |
          const whoToGreet = core.getInput('who-to-greet')
          core.notice(`Hello ${whoToGreet}`)
          core.setOutput('answer', 42)

          if (context.eventName === 'issues' && context.payload.action === 'opened') {
           await github.rest.issues.createComment({
             issue_number: context.issue.number,
             owner: context.repo.owner,
             repo: context.repo.repo,
             body: 'Thanks for reporting!'
           })
          }
